W7D2/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resource :session
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end

  root to: redirect('/cats')
end

W7D2/app/models/user.rb
class User < ApplicationRecord
  validates :user_name, :session_token, presence: true, uniqueness: true  
  validates :password_digest, presence: true 
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_accessor :password
  after_initialize :ensure_session_token  #before validation will only reun before .save is called , 

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save
    self.session_token 
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def self.find_by_credentials(user_name, password)
    user = User.find_by(user_name: user_name)
    return nil unless user

    user.is_password?(password) ? user : nil 
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

end

W7D2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logout, only: [:new]

  def index 
    @users = User.all 
    render :index 
  end

  def new
    render :new
  end

  def create
    @user = User.new(user_params) 
    if @user.save 
      login(@user)
      redirect_to cats_url 
    else  
      render @user.errors.full_messages 
    end
  end

  private 
  def user_params 
    params.require(:user).permit(:user_name, :password)
  end

end

W7D2/app/views/users/index.html.erb
<% @users.each do |user| %>
  <ul>
  <li><%= user.user_name %></li>
  </ul>
<% end %>

W7D2/app/views/users/new.html.erb
<h1>Sign Up 😄</h1>


<form action="<%= users_url %>" method="POST">
    <label for="username">
        Username:
        <input type="text" id="username" name="user[user_name]">
    </label>
    <label for="password">
        Password:
        <input type="password" id="password" name="user[password]">
    </label>

    <input type="submit" value="Submit">
</form>